version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: BigPassword
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build:
      context: .  # Path to Dockerfile
      dockerfile: Dockerfile
    container_name: flask_app
    depends_on:
      - db
    environment:
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_NAME=db
      - SECRET_KEY=J4F3K2n!t92heJds91kVd8@2LkfjQf&22
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask_app.rule=Host(`quantumtimecapsule.com`)"
      - "traefik.http.routers.flask_app.entrypoints=websecure"
      - "traefik.http.routers.flask_app.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.flask_app-secure.middlewares=redirect-to-https"
    ports:
      - "5000:5000"
    #volumes:
      #- "."  # Mount volume for live updates

  traefik:
    image: traefik:v3.1.4
    container_name: traefik_proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=contact@quantumtimecapsule.com"  # Valid email address
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt  # Store SSL certificates

volumes:
  db_data:
